package com.tts.subscriberlist.subscriber;
//package above and imports below
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.boot.autoconfigure.condition.ConditionalOnCloudPlatform;
import javax.persistence.*;
import java.util.Date;

@Entity
//Specifies that the class is an entity. This annotation is applied to the entity class.

public class Subscriber {

    @Id
    //sets the 'id' as the primary key
    @GeneratedValue(strategy = GenerationType.AUTO)
    //allows the id to be generated by the underlying database

    private Long id;
    private String firstName;
    private String lastName;
    private String userName;

    @Column
    //allows the date to be generated by the system

    @CreationTimestamp
    private Date signedUp;

    public Subscriber() {
        //non-argument constructor needed for JPA
    }

    //other constructor and methods continue below
    public Subscriber(String firstName,String lastName,String userName,Date signedUp){
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.signedUp = signedUp;

    }

    //Getters and Setters
    public String getFirstName() {return firstName;}

    public void setFirstName(String firstName) {this.firstName = firstName;}

    public String getLastName() {return lastName;}

    public void setLastName(String lastName) {this.lastName = lastName;}

    public String getUserName() {return userName;}

    public void setUserName(String userName) {this.userName = userName;}

    public Date getSignedUp() {return signedUp;}

    public void setSignedUp(Date signedUp) {this.signedUp = signedUp;}

    // Override toString

    @Override
    public String toString() {
        return "Subscriber{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", userName='" + userName + '\'' +
                ", signedUp=" + signedUp +
                '}';
    }

}


